name: cloudflare_turnstile
description: A free CAPTCHAs alternative to enhance security and protect against bots.
repository: https://github.com/Nika0000/cloudflare_turnstile
version: 2.0.3

platforms:
  android:
  ios:
  web:

environment:
  sdk: ^3.2.3
  flutter: ">=3.16.6"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.4
  webview_flutter_wkwebview: ^3.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

topics:
  - hcaptcha
  - recaptcha
  - cloudflare-turnstile