name: cloudflare_turnstile
description: A free CAPTCHAs alternative to enhance security and protect against bots.
repository: https://github.com/Nika0000/cloudflare_turnstile
version: 3.0.1

platforms:
  android:
  ios:
  web:

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

topics:
  - hcaptcha
  - recaptcha
  - cloudflare-turnstile