name: cloudflare_turnstile
description: A free CAPTCHAs alternative to enhance security and protect against bots.
repository: https://github.com/Nika0000/cloudflare_turnstile
version: 0.4.0

platforms:
  android:
  ios:
  web:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview_android: ^1.0.13
  flutter_inappwebview_ios: ^1.0.13
  flutter_inappwebview_platform_interface: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

topics:
  - hcaptcha
  - recaptcha
  - cloudflare-turnstile